algoritmo "BEE 1002 - area_do_circulo"
// A fórmula para calcular a área de uma circunferência é: area = p . raio2.
//Considerando para este problema que p = 3.14159:
//Efetue o cálculo da área, elevando o valor de raio
//ao quadrado e multiplicando por p.
var

raio, area : real
inicio

escreva("Informe o valor do raio: ")
leia(raio)

area <- pi * raio^2

escreval("A=",area:1:4)
// Seção de Comandos 
fimalgoritmo
