algoritmo "ex2-Produto_Simples"
// Leia dois valores inteiros.A seguir, calcule o produto entre estes
//dois valores e atribua esta operação à variável PROD.
//A seguir mostre a variável PROD com mensagem correspondente.
var
n1,n2,prod: inteiro

inicio
     escreva("Informe o primeiro valor ")
     leia(n1)
     
     escreva("Informe o segundo valor ")
     leia(n2)
     
     prod <- n1*n2
     
     escreval("PROD = ",prod)
     

fimalgoritmo
